### ISSUE TITLE
weighted_networks$lr_sig missing

### ISSUE THREAD

**Issue by Jeron1996** [saeyslab/nichenetr#36] opened 2020-06-12 08:06 UTC
Hi,

Thanks for developing this great package.

I am trying to use it to interrogate my Seurat object using nichenet_seuratobj_aggregate(). Unfortunately, I run into trouble when I try to use the weighted_network object. I cannot download it using the provided link, as a matter of fact none of the objects can be downloaded using the zenodo server.

```
> weighted_networks = readRDS(url("https://zenodo.org/record/3260758/files/weighted_networks.rds"))
Error in readRDS(url("https://zenodo.org/record/3260758/files/weighted_networks.rds")) : 
  cannot open the connection
In addition: Warning message:
In readRDS(url("https://zenodo.org/record/3260758/files/weighted_networks.rds")) :
  InternetOpenUrl failed: 'The operation timed out'
```

I can download the files using my browser but then the weighted_networks is missing the weighted_networks$lr_sig column. Do you have any suggestions?

```
> weighted_networks_lr = weighted_networks$lr_sig %>% inner_join(lr_network %>% distinct(from,to), by = c("from","to"))
Error in UseMethod("inner_join") : 
  no applicable method for 'inner_join' applied to an object of class "NULL"
In addition: Warning message:
Unknown or uninitialised column: `lr_sig`. 
```

**Comment by browaeysrobin** [comment] 2020-06-12 13:41
Hi @Jeron1996 

That you cannot download the files directly in R via this link is probably due to suboptimal internet or a temporary issue with the Zenodo server. I just tested it, and had no problem downloading it from within R.

I also downloaded the weighted_networks file from the browser, but in my case both the $lr_sig and $gr slots were present as should be, so I could not reproduce your errors. Maybe this has to do with internet/Zenodo server issues as well. 

I will close this issue now, because this does not seem to be a nichenetr problem.

**Closed by browaeysrobin** 2020-06-12 13:41 UTC
